### ISSUE TITLE
key/values not propogating into downstream tasks

### ISSUE THREAD

**Issue by warroyo** [regevbr/keyval-resource#8]
I am seeing that when i have  2+ tasks in a job the key values are not being passed to the next task. both tasks have inputs and outputs for the key/values

**Comment by regevbr** [comment]
@ezraroi can you please check your pipeline cf file and see how we handle this scenario?

**Comment by ezraroi** [comment]
It is working fine.. Example of a job:
![image](https://user-images.githubusercontent.com/5808368/37563485-76b9d39e-2a8a-11e8-946a-c5b4c8eb78a9.png)

**Comment by regevbr** [comment]
@ezraroi are you sure that changes in the first task propagate to the second task? I remember it does but can you see it in the ui?

**Comment by warroyo** [comment]
@ezraroi what does your task.yml file look like?

**Comment by ezraroi** [comment]
```yml
platform: linux

image_resource:
  type: docker-image
  source:
    repository: hub.docker.intel.com/swce-docker/pipeline-base

inputs:
  - name: tools
  - name: repo
  - name: keyval

outputs:
  - name: out
  - name: keyvalout

caches:
  - path: gradle
  - path: maven
  - path: npm

run:
  path: tools/tasks/task.sh
```
